var ROSTER = [
  {
    "IsCaptain": "CAPTAIN",
    "Name": "Clare Frantz",
    "Email": "clare.frantz12@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "FemalePARTNERED",
    "Partner/Baggage": "Matthew Marcus",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club"
  },
  {
    "IsCaptain": "CAPTAIN",
    "Name": "Allen Jones",
    "Email": "allenjones.mo@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club"
  },
  {
    "IsCaptain": "",
    "Name": "Amanda Borders",
    "Email": "amandaborders91@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "FemaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "CAPTAIN",
    "Name": "Amanda johnson",
    "Email": "Aj10788@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "FemalePARTNERED",
    "Partner/Baggage": "TR",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club"
  },
  {
    "IsCaptain": "",
    "Name": "Brian Ebbitts",
    "Email": "bebbitts@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Brock Hicks",
    "Email": "Bahicks99@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "MalePARTNERED",
    "Partner/Baggage": "Sowmya",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Caleb Cauthon",
    "Email": "calebcauthon@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Cam Hunter",
    "Email": "Cameron.Hunter15@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Christian Simpson",
    "Email": "cwsimpson@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "all",
    "Experience": "club"
  },
  {
    "IsCaptain": "",
    "Name": "Cory Green",
    "Email": "green.1065@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Courtney Walbe",
    "Email": "cwalbe@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "FemaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Daniel Tixier",
    "Email": "Dgtixier@pm.me",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club"
  },
  {
    "IsCaptain": "",
    "Name": "Gabriel Valencia",
    "Email": "gabev13@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "MalePARTNERED",
    "Partner/Baggage": "Jordan Eissner",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Handel Aiken",
    "Email": "Handel.aiken@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Janani Ragothaman",
    "Email": "jsragothaman@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "FemaleSOLO",
    "Partner/Baggage": "",
    "October 27": "",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "November 3, November 10, November 17",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Jeffrey Rehm",
    "Email": "Jeffrehm180@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "MalePARTNERED",
    "Partner/Baggage": "Joe Young",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Jenna Galletta",
    "Email": "jgalletta19@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "FemaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Joe Young",
    "Email": "ijustwantmymail@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "MalePARTNERED",
    "Partner/Baggage": "Jeff Rehm",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Jonah Larsen",
    "Email": "j3sports@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club"
  },
  {
    "IsCaptain": "",
    "Name": "Jordan Becquer",
    "Email": "jjbecquer@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Jordan Eissner",
    "Email": "jordaneissner@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "FemalePARTNERED",
    "Partner/Baggage": "Gabe Valencia",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Jordan Warren",
    "Email": "jordan.mechele@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "FemaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club"
  },
  {
    "IsCaptain": "",
    "Name": "Karissa Jenesse",
    "Email": "Kjenesse.27@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "FemalePARTNERED",
    "Partner/Baggage": "Kieu Duong",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Kieu Duong",
    "Email": "kieuduong0720@yahoo.com",
    "Identifying Gender": "Male",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "MalePARTNERED",
    "Partner/Baggage": "Karissa Jenesse",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Kirsten Fahlbusch",
    "Email": "kirsten.fahlbusch@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "FemalePARTNERED",
    "Partner/Baggage": "Zach Nager",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club"
  },
  {
    "IsCaptain": "",
    "Name": "Luke Grieger",
    "Email": "lgrieger13@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "MalePARTNERED",
    "Partner/Baggage": "Spencer Roberts",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "CAPTAIN",
    "Name": "Matthew Marcus",
    "Email": "matthew.marcus@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "MalePARTNERED",
    "Partner/Baggage": "Clare Frantz",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Mei Branit",
    "Email": "meibranit@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "FemaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club"
  },
  {
    "IsCaptain": "",
    "Name": "Michael Montesano",
    "Email": "montym17@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "CAPTAIN",
    "Name": "PJ Matulka",
    "Email": "Peter.matulka@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Rebekah Seyfert",
    "Email": "Rseyfert1@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "FemaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Ryan Tuschhoff",
    "Email": "ryantuschhoff@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Sam Ward (Suds)",
    "Email": "Samgwhward@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Sowmya Ragothaman",
    "Email": "ragothaman98@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "FemalePARTNERED",
    "Partner/Baggage": "Brock",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 17",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Spencer Roberts",
    "Email": "Spence1529@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "MalePARTNERED",
    "Partner/Baggage": "Luke Grieger",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club"
  },
  {
    "IsCaptain": "",
    "Name": "Steph Rupp",
    "Email": "stephrupp@gmail.com",
    "Identifying Gender": "Female",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "FemaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "CAPTAIN",
    "Name": "Tim Robbins",
    "Email": "TimBRobbins@Gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "MalePARTNERED",
    "Partner/Baggage": "Skittles",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17, November 24 (day before Thanksgiving)",
    "Experience": "Club"
  },
  {
    "IsCaptain": "",
    "Name": "Wheels",
    "Email": "Mjwheelock77@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "SOLO",
    "GenderAndPartnerStatus": "MaleSOLO",
    "Partner/Baggage": "",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 24 (day before Thanksgiving)",
    "Experience": "Club, College, Summer League"
  },
  {
    "IsCaptain": "",
    "Name": "Zach Nager",
    "Email": "znager@gmail.com",
    "Identifying Gender": "Male",
    "IsPartnered": "PARTNERED",
    "GenderAndPartnerStatus": "MalePARTNERED",
    "Partner/Baggage": "Kirsten Fahlbusch",
    "October 27": "Week 1",
    "November 3": "Week 2",
    "November 10": "Week 3",
    "November 17": "Week 4",
    "Attendance, 6:00-8:00PM each night": "October 27, November 3, November 10, November 17",
    "Experience": "Club"
  }
]